# Generated by Django 4.1.1 on 2022-09-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmanager',
            name='category',
        ),
        migrations.AddField(
            model_name='taskmanager',
            name='hist',
            field=models.CharField(blank=True, choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('IOT', 'Internet of Things')], default='ML', max_length=10, null=True),
        ),
    ]
